"""
============================================================================
Tokyo Open Data Hackathon 2026 — Heat Stroke Prevention Project
api.py — HTTP layer for the two features this half of the team owns.

WHY THIS FILE EXISTS: Python can't "collect" a live GPS location on its
own — that only exists on the user's device (a phone's GPS, or a browser's
Geolocation API). So the actual flow is:

  device GPS  --(frontend JS/app)-->  HTTP request to this API  --> Python

This file is that HTTP layer: it wraps nearby_cool_spots() and
classify_for_profile() as endpoints your teammates' frontend can call with
whatever coordinates the device reports. It is NOT the frontend — see
location_test.html next to this file for a minimal (ugly, on purpose)
test harness that exercises these endpoints from a browser, so you can
verify your two features work end-to-end without waiting on the rest of
the team, and so your teammates have a concrete example of what to call.

  pip install fastapi uvicorn
  uvicorn api:app --reload --host 0.0.0.0 --port 8000

Then e.g.:
  GET http://localhost:8000/wbgt/status
  GET http://localhost:8000/wbgt/personalized?age=70
  GET http://localhost:8000/nearby-cool-spots?lat=35.69&lon=139.70&age=70

Interactive API docs (auto-generated by FastAPI, useful for your teammates
to explore the contract themselves): http://localhost:8000/docs

NOTE ON REAL PUSH NOTIFICATIONS: this API is "pull" style — a client asks
"is it dangerous for me right now?" whenever it wants (e.g. on app open,
or every N minutes while the app is foregrounded). True background push
(an alert that arrives even with the app closed) needs a push service
(web push / Firebase Cloud Messaging / APNs) wired up on the frontend side,
using this endpoint's "alert" boolean as the trigger condition. That's a
frontend/mobile infra decision for your teammates, not something this
Python layer decides on its own.
============================================================================
"""

import json
from typing import Optional

from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware

from WBGT_Monitor import STATUS_PATH as WBGT_STATUS_PATH, classify_for_profile
from Nearby_Cool_Spots import nearby_cool_spots

app = FastAPI(title="Tokyo Heat Stroke Prevention API", version="0.1")

# allow_origins=["*"] is fine for a hackathon demo (lets location_test.html
# and any frontend dev server call this freely). Lock this down to your
# real frontend's origin before this goes anywhere near production.
app.add_middleware(
    CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"],
)


def _load_wbgt_status():
    if not WBGT_STATUS_PATH.exists():
        raise HTTPException(
            status_code=503,
            detail="No WBGT reading yet. Run WBGT_Monitor.py at least once first.",
        )
    with open(WBGT_STATUS_PATH, encoding="utf-8") as f:
        return json.load(f)


def _profile_from_query(age, is_pregnant, has_chronic_condition):
    return {"age": age, "is_pregnant": is_pregnant, "has_chronic_condition": has_chronic_condition}


@app.get("/wbgt/status")
def wbgt_status():
    """Raw, un-personalized reading — the same thing WBGT_Monitor.py writes
    to outputs/WBGT_Current_Status.json each poll."""
    return _load_wbgt_status()


@app.get("/wbgt/personalized")
def wbgt_personalized(
    age: Optional[int] = Query(None, ge=0, le=120, description="user's age in years"),
    is_pregnant: bool = Query(False),
    has_chronic_condition: bool = Query(False),
):
    """Same underlying WBGT reading, but the alert threshold is adjusted
    for the given profile — see WBGT_Monitor.classify_for_profile()."""
    status = _load_wbgt_status()
    profile = _profile_from_query(age, is_pregnant, has_chronic_condition)
    return classify_for_profile(status["wbgt_c"], profile)


@app.get("/nearby-cool-spots")
def nearby_cool_spots_endpoint(
    lat: float = Query(..., ge=-90, le=90),
    lon: float = Query(..., ge=-180, le=180),
    radius_m: int = Query(800, gt=0, le=5000),
    top_n: int = Query(5, gt=0, le=20),
    age: Optional[int] = Query(None, ge=0, le=120),
    is_pregnant: bool = Query(False),
    has_chronic_condition: bool = Query(False),
):
    """This is the endpoint your teammates' frontend calls with the
    device's live lat/lon (from navigator.geolocation in a browser, or the
    platform location API in a native app)."""
    profile = _profile_from_query(age, is_pregnant, has_chronic_condition)
    try:
        return nearby_cool_spots(lat, lon, radius_m=radius_m, top_n=top_n, profile=profile)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))